version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts/build_and_publish.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: scripts/start_server.ps1
      timeout: 300
      runas: Administrator
