version: 0.0
os: windows
files:
  - source: PipelineTesting/
    destination: C:\inetpub\wwwroot\MyWebApi
hooks:
  BeforeInstall:
    - location: scripts\install_dotnet_runtime.ps1
      timeout: 300
      runas: Administrator
    - location: scripts\install_iis.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts\configure_iis.ps1
      timeout: 300
      runas: Administrator
